-- AlterTable
ALTER TABLE "ReserveTent" ADD COLUMN     "kids" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "kidsPrice" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Tent" ADD COLUMN     "kids_bundle_price" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "max_kids" INTEGER NOT NULL DEFAULT 1;
